global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.IO;
global using System.Reflection;
global using BepInEx;
global using BepInEx.Bootstrap;
global using BepInEx.Configuration;
global using UnityEngine;
